"use client";
import { motion } from "framer-motion";
import { useId, useMemo } from "react";
import DottedMap from "dotted-map";

// Generated at build time by scripts/gen-world-map.mjs — keep options in sync.
const WORLD_MAP_SRC = "/world-map.svg";
import { cn } from "@/lib/utils";

interface Point {
  lat: number;
  lng: number;
  label?: string;
}

interface WorldMapProps {
  points: Point[];
  /** Pairs of indexes into `points` to draw arcs between. */
  arcs?: Array<[number, number]>;
  lineColor?: string;
  pointColor?: string;
  labelColor?: string;
  className?: string;
}

/**
 * Dotted world map with animated arcs between geographic points.
 * Lightweight: pure SVG, no external map libs.
 */
export function WorldMap({
  points,
  arcs = [],
  lineColor = "#A15BF1",
  pointColor = "#1FA6C1",
  labelColor = "#0F1729",
  className,
}: WorldMapProps) {
  const id = useId();

  // The dotted map artwork itself is a static asset generated by
  // scripts/gen-world-map.mjs; inlining it as a data: URI put 341 KB into
  // about/index.html. We still build a DottedMap here for its projection, so
  // pins land on the right country.
  const { vbW, vbH, projected } = useMemo(() => {
    const map = new DottedMap({ height: 60, grid: "diagonal" });
    const projected = points.map((p) => {
      const pin = map.getPin({ lat: p.lat, lng: p.lng });
      return pin ? { x: pin.x, y: pin.y } : { x: 0, y: 0 };
    });
    return {
      vbW: map.image.width,
      vbH: map.image.height,
      projected,
    };
  }, [points]);

  const arcPath = (ai: number, bi: number) => {
    const pa = projected[ai];
    const pb = projected[bi];
    const mx = (pa.x + pb.x) / 2;
    const my = (pa.y + pb.y) / 2 - Math.abs(pa.x - pb.x) * 0.35;
    return `M ${pa.x} ${pa.y} Q ${mx} ${my} ${pb.x} ${pb.y}`;
  };

  return (
    <div className={cn("w-full", className)}>
      <div className="relative w-full">
        <img
          src={WORLD_MAP_SRC}
          alt=""
          aria-hidden
          className="w-full h-auto pointer-events-none select-none [mask-image:linear-gradient(to_bottom,transparent,black_15%,black_85%,transparent)]"
          draggable={false}
        />
        <svg viewBox={`0 0 ${vbW} ${vbH}`} className="absolute inset-0 w-full h-full">
        <defs>
          <linearGradient id={`${id}-line`} x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="#1FA6C1" />
            <stop offset="100%" stopColor="#A15BF1" />
          </linearGradient>
        </defs>

        {arcs.map(([i, j], k) => {
          const a = points[i];
          const b = points[j];
          if (!a || !b) return null;
          return (
            <motion.path
              key={k}
              d={arcPath(i, j)}
              fill="none"
              stroke={`url(#${id}-line)`}
              strokeWidth={0.4}
              strokeLinecap="round"
              initial={{ pathLength: 0, opacity: 0 }}
              whileInView={{ pathLength: 1, opacity: 1 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 1.8, ease: "easeInOut", delay: 0.3 + k * 0.4 }}
            />
          );
        })}

        {points.map((p, i) => {
          const { x, y } = projected[i];
          return (
            <g key={i}>
              <circle cx={x} cy={y} r={0.9} fill={pointColor} />
              <motion.circle
                cx={x}
                cy={y}
                r={0.9}
                fill="none"
                stroke={pointColor}
                strokeWidth={0.3}
                initial={{ scale: 1, opacity: 0.8 }}
                animate={{ scale: 3, opacity: 0 }}
                transition={{ duration: 2, repeat: Infinity, ease: "easeOut", delay: i * 0.3 }}
                style={{ transformOrigin: `${x}px ${y}px` }}
              />
              {p.label && (
                <text
                  x={x + 1.6}
                  y={y - 1.4}
                  fontSize={2.4}
                  fontWeight={700}
                  fill={labelColor}
                  style={{ fontFamily: '"Plus Jakarta Sans", sans-serif' }}
                >
                  {p.label}
                </text>
              )}
            </g>
          );
        })}
        </svg>
      </div>
    </div>
  );
}